title: sembio/go
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for semantic Bioinformatics in Go

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-remote-theme
